### ISSUE TITLE
Is it possible to change the number of signals to less than 32?

### ISSUE THREAD

**Issue by Brianthechemist** [kethort/Mach4ModbusArduinoMegaW5500#10]
Your installer looks awesome, definitely way faster than manual editing in mach4. 

My only issue is that i will be adapting this to a portenta h7 machine control board and it has nowhere as many i/o as a mega (plus, the external i/o is all via i2c so port commands won’t work).

Is it possible to change the number of inputs/outputs/holding registers that your installer adds to Mach? (There’s probably an ini file or something within your python code, but i’m not a python guy).

i think that your arduino examples are enough to do the arduino side (i need more communication then i/o toggling).

If you have a reference how to programmatically edit the mach 4 screenset that would be useful. Manually adding buttons and setting their function via the screen editor is super time consuming!

**Comment by kethort** [comment]
Hello,

Please don’t raise issues here unless there is an issue with the hardware/software. In the last issue you raised I gave you a link to another repo that has examples of editing the screen externally. I don’t recommend manually editing the Mach4 screen.xml files or the Machine.ini files because they are easy to break.

But if you want to:
In the profile folder in the Mach4 directory (your named profile), you can find the the Machine.ini file, which contains settings for modbus functions and registers. An example ini file is in this repo. To edit the scripts and GUI manually, you can edit the Screen.xml file for your profile. It’s much easier to use Mach4 to configure this, and less chance of breaking the profile. The only reason I used a Python script/program to edit those files, is so anyone using this repo could easily setup this specific device by just defining an ip address and pressing install.

I have never manually edited the GUI before, but I definitely wouldn’t recommend it, since it’s all XML and Mach4 is much easier with pick and place components. It’s all in the screen.set zip file and it should be a giant screen.xml file. After you edit it you have to re-zip it as a screen.set zip directory.

**Comment by Brianthechemist** [comment]
Sorry, I didn’t see the option for ‘new feature’ for some reason. It only
lets me make issues.

I was actually hoping for help editing the contents of what the python
script inserts

Thanks!

**Comment by kethort** [comment]
The Python script is commented. Typically in code, if a function has a useful name like ‘machini_ini_to_dict’ it doesn’t need a huge explanation. It turns the Machine.ini file into a Python dictionary with key:value pairs where the key is the Mach4 register and the value is what is set in Mach4. You can actually read these between both files by going into the Mach4 settings, or modbus plugin settings and compare the information. I did comment the functions though, they are delimited underneath with a # sign.

But the installer in the other repo actually unzips the ‘screen.set’ directory, looks for the scripts in the ScreenLoad and PLC LUA scripts and actually changes the LUA code and then rezips the screen.set zip file. It’s just an xml file parsed using a Python library but It’s really useful if you can understand the code. And under each function, a comment exists and for the weird ‘going on stuff too’. The comments are denoted with a # sign in Python. The function names says what it does. For example, it checks if Mach4 is currently open and tells you to close it first in a ‘is_mach_running’ function or something similar to that. It even tries to find the Arduino by IP address in another function by vendor ID in the MAC address. There’s so many Arduinos out there that the IP function may not work, and it needs to be in the ARP table before it can be recognized, but the IP address text box is editable for that reason.

Sorry I didn’t go further with this but the other repo on my account with ESP32 and the MPG handwheel with TCP modbus might help you better. I never did anything with the Mach4 GUI but if you parse the screen.xml file like I did using the xml reader library in Python, you can do anything you want to it, programmatically.

the main reason I didn’t go any further with this is because it’s only meant to be a large GPIO expander, and the way I coded the Arduino script in this is a little more advanced, since I’m not using the standard digitalread and digitalwrite functions of the Arduino because you want faster GPIO switching on a real machine. So, I’m using Atmel pins and ports, which is a lower ‘at the hardware level’ reading/writing (takes less ms to perform). But that requires ALOT of binary bit switching/manipulation. And if you separate the GPIO in half like I did for the inputs/outputs…it was the simplest way I could do it, without a crap ton of code. If you look at the comment at the head of the Arduino file, it translates the binary bit positions to the GPIO. I’m just reading/writing based on changes at the PORT/PIN ‘level’ of the hardware. 

the other repo is ‘Arduino-like’ as it is written with digitalread/writes API, and it also contains code in the installer that manipulates the screen.set zip file using Python. 

I made these repos specific to a certain task and was thinking most people would just make the projects ‘as-is’ and just use the installer instead of using the code, but there is ALOT of useful code to make something on your own. 

The weird GUI stuff in the class init() function of the Python code is just GUI code using wxPython. Mach4 uses wxLua. It’s all based on wxWidgets and wxFormBuilder. The forms are also included in this repo. wxFormBuilder will write the wxPython code for you, just follow my formatting and don’t include everything it outputs. I didn’t comment the GUI stuff in wxPython for that reason, but it makes sense once you use wxFormBuilder and get the output of that. GUI code is always gross looking, but it’s ridiculously useful because it handles context switching and ‘GUI ISR’s’ for you. You can even use that form builder to make Mach4 stuff like wizards and prompts or other things with the LUA output. The wxPython was built into a Windows .exe using py2exe and that is what the dist/ folder contains.

**Comment by kethort** [comment]
The event handlers of the gui are the ‘GUI ISR’s’ I was talking about. Like a button press or combo box pressed event. It’s like context switching even though it’s really a top-down event loop procedure

**Comment by Brianthechemist** [comment]
That's great.  I really like the clever way you did the bit manipulation
for the ports, I was hoping to do something similar until I saw the
architecture of the Portenta board.  I actually found your code for the
float and coil reading stashed away in the examples folder the most useful
in my application.  I'll poke around in the code, now that I know where to
look.  I'm certainly not a python expert, but I can edit existing code no
problem if I know where to look!  I've done some pretty involved
customization to the LUA code and screen set, but I hadn't found the right
place in the zip file to programmatically edit the GUI part.

As an aside, there is something I've been trying to do with the wx
screenset that I think the whole Mach4 community could appreciate:  resize
the current screens to 16:9 (HD, 4K displays) format instead of the 4:3
(1024x768) it is now.  I think that your python "heavy lifting" is the key
to doing this.  Mach will happily resize the screenset to fill any monitor
at runtime, but if you insert any bitmap or image, it also gets stretched
out due to the rescaling, making it impossible to read.  If you instead
change the default screen resolution in the editor, it simply adds
additional space around it leaving all of the existing elements taking up a
small space.  I'd like to apply the same rescaling to the screenset
directly so it is possible to edit the wider screen layout with the
buttons/tabs/windows/etc already resized.  I'm sure it is a simple
calculation that Mach does, but it is not just a simple scaling of every
value.  There is some intelligence to it.

I'm thinking that it should be possible to "find, calculate and replace"
the references to the positions and horizontal sizes of the screen elements
the same way you have the python code editing the tabs and buttons.

Thanks for the help!  I'll let you know how I get on.  maybe we can take
this discussion offline though to keep from cluttering up your repo.

**Comment by kethort** [comment]
Typically for a CNC machine, you don’t need an expensive computer or display to operate it, and Mach4 isn’t a resource heavy program. Most professional industry CNC machines have motion controllers that are purely embedded, with no desktop computers needed to interact with the motion controlling hardware. In a factory environment, it’s ideal to have the least amount of failure points and to have inexpensive/readily available components in case of failures. And computers and monitors are usually the weakest link in the chain. If a company does choose to use Mach4 with an external motion controller for their CNC machine, they typically use very inexpensive computers and standard 1920x1080 displays for these reasons. They also rarely ever connect the computer to the internet, to avoid viruses and nagging windows updates that could affect other programs and startup items. ideally, once you have the Mach4 program setup and running on a machine, you rarely want to update it with the latest Mach4 software. Although a 4K screen could work with Mach4, it may not be practical on an actual machine in a factory. If that display were to fail because of wood chips clogging up the heat dissipation, or a high voltage plasma machine short, it would simply cost way too much money to replace a display like that. I used to program the firmware for motion controllers and sometimes install hardware/software in machines and the buggiest things always happened with the computers and monitors. Some of the bigger companies would ask if they could use a Mac Mini for running Mach4 and it really was just a comedic moment for me. It would cost way too much money to do that for a machine that would run itself after setup most of the time. Most CNC operators want to ‘set it and forget it’, and typically can’t debug computer issues. It would be a nice feature to have, but likely impractical for everyday use.

you commented and also probably found this repo on the Mach support forum. If you have any questions just message me there and I’ll try to help. A lot of my posts there have unique upgrades through software and explanations of things not explained by Mach4 documentation.

**Comment by Brianthechemist** [comment]
1920x1080 is 16:9 (same aspect as 4k).  I’m asking to go to 1920x1080 for
exactly the reasons you suggest :)

I agree with all of your points.

I’m actually using an old intel NUC and a used touchscreen monitor for mine
:)

**Comment by Brianthechemist** [comment]
The current screen layout is made for old 1024x768 monitors, which are the
same aspect ratio as TV (4:3).
